### ISSUE TITLE
Failure when using special characters like ' or " in communication

### ISSUE THREAD

**Issue by thiscor** [thiscor/tamalone#10]
Try to type " or ' characters in an online (chat) conversation.

Possible solution: Protect JSON serialisation and encode all strings typed by users.

**Comment by pietk** [comment]
Fixed by 9adcc6b79d1ba1e76c07e47b8e8c5ed24738d3de

**Comment by tamalone** [comment]
Already Published to https://tamalone-test.appspot.com ?  Still failing


![json_quotes_issue_ 10](https://cloud.githubusercontent.com/assets/11886460/7133521/7b52ec56-e294-11e4-966c-9f3633a6b0c9.JPG)

**Comment by tamalone** [comment]
Tested, not available in build
